In [ ]:
import pandas as pd
df = pd.read_csv('student_300MB.csv')

# Agregar registro_id unico para los usuarios

In [6]:
df['registro_id'] = ['E' + str(i).zfill(8) for i in range(1, len(df) + 1)]
print(df[['registro_id', 'student_id']])

        registro_id  student_id
0         E00000001         562
1         E00000002         717
2         E00000003         167
3         E00000004         266
4         E00000005          58
...             ...         ...
2501831   E02501832         109
2501832   E02501833         956
2501833   E02501834         789
2501834   E02501835         180
2501835   E02501836         611

[2501836 rows x 2 columns]

In [29]:
df

,student_id,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,...,G1_mat,G2_mat,G3_mat,studytime_por,failures_por,schoolsup_por,G1_por,G2_por,G3_por,registro_id
0,562,GP,F,16,R,GT3,A,4,3,other,...,7,9,1,1,3,no,10,9,9,E00000001
1,717,GP,F,18,U,GT3,T,4,4,other,...,9,13,16,2,0,no,14,19,15,E00000002
2,167,GP,M,16,U,GT3,T,3,3,services,...,13,1,0,1,0,no,10,12,12,E00000003
3,266,GP,F,17,U,LE3,T,2,2,at_home,...,12,9,12,3,0,no,14,16,16,E00000004
4,58,GP,M,15,U,LE3,A,1,2,other,...,12,13,10,1,0,no,9,12,11,E00000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2501831,109,GP,F,16,R,GT3,T,3,4,at_home,...,7,8,8,3,0,no,9,11,11,E02501832
2501832,956,MS,F,17,R,GT3,T,1,1,teacher,...,9,13,15,2,0,no,9,11,15,E02501833
2501833,789,GP,M,17,U,GT3,T,1,1,at_home,...,11,0,11,3,0,no,9,8,14,E02501834
2501834,180,MS,M,16,U,GT3,T,3,3,services,...,17,15,13,2,1,no,10,11,11,E02501835
2501835,611,GP,F,17,U,LE3,T,1,2,at_home,...,11,13,13,1,1,no,8,9,11,E02501836

# Creando Users.csv

## Extraer los registro_id del dataset de students

In [ ]:
df_users = df[['registro_id']].copy()
print(df_users)

        registro_id
0         E00000001
1         E00000002
2         E00000003
3         E00000004
4         E00000005
...             ...
2501831   E02501832
2501832   E02501833
2501833   E02501834
2501834   E02501835
2501835   E02501836

[2501836 rows x 1 columns]

In [ ]:
import pandas as pd
import random
from faker import Faker

fake = Faker('es_ES')
num_registros = len(df_users)

def generar_contraseña():
    return ''.join(random.choices("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890", k=10))

nombres1, nombres2, apellidos1, apellidos2, correos, contrasenas = [], [], [], [], [], []
correos_existentes = set()

for i in range(num_registros):
    nombre_completo = fake.name().split()

    if len(nombre_completo) >= 4:
        nombre1, nombre2, apellido1, apellido2 = nombre_completo[:4]
    elif len(nombre_completo) == 3:
        nombre1, nombre2, apellido1 = nombre_completo
        apellido2 = fake.last_name()
    else:
        nombre1 = nombre_completo[0]
        nombre2 = fake.first_name()
        apellido1 = fake.last_name()
        apellido2 = fake.last_name()

    base = f"{nombre1.lower()}.{apellido1.lower()}"
    sufijo = ""
    dominio = "@utec.edu.pe"
    correo = base + dominio

    for letra in apellido2.lower():
        if correo not in correos_existentes:
            break
        sufijo += letra
        correo = base + sufijo + dominio

    contador = 1
    while correo in correos_existentes:
        correo = base + sufijo + str(contador) + dominio
        contador += 1

    correos_existentes.add(correo)

    nombres1.append(nombre1)
    nombres2.append(nombre2)
    apellidos1.append(apellido1)
    apellidos2.append(apellido2)
    correos.append(correo)
    contrasenas.append(generar_contraseña())

df_users['nombre1'] = nombres1
df_users['nombre2'] = nombres2
df_users['apellido1'] = apellidos1
df_users['apellido2'] = apellidos2
df_users['correo'] = correos
df_users['contraseña'] = contrasenas

print(df_users)

        registro_id     nombre1   nombre2  apellido1 apellido2  \
0         E00000001        Maxi  Aragonés     Codina  Talavera
1         E00000002  Candelario     Prats    Pozuelo  Torrijos
2         E00000003     Rosenda     Ester      Boada   Salcedo
3         E00000004      Xavier  Nicodemo   Castillo   Atienza
4         E00000005    Marisela  Valentín  Contreras     Camps
...             ...         ...       ...        ...       ...
2501831   E02501832        Ruth   Narváez     Llobet    Murcia
2501832   E02501833    Reinaldo        de    Arévalo      Bayo
2501833   E02501834        Aroa   Sanjuan      Uribe      Rosa
2501834   E02501835   Severiano   Clavero      Rueda      Amat
2501835   E02501836        Omar        de      Lerma  Bejarano

                                 correo  contraseña
0               maxi.codina@utec.edu.pe  FMa9z2vhgY
1        candelario.pozuelo@utec.edu.pe  6VRBDjaqQ1
2             rosenda.boada@utec.edu.pe  qaWoCEAOK6
3           xavier.castillo@utec.edu.pe  t1n9lvmB9s
4        marisela.contreras@utec.edu.pe  jCzgtVVRl8
...                                 ...         ...
2501831        ruth.llobetm@utec.edu.pe  bWG3aXxfx2
2501832   reinaldo.arévalob@utec.edu.pe  cCgNS0Dxs4
2501833         aroa.uriber@utec.edu.pe  DIQy7vGmSl
2501834    severiano.ruedaa@utec.edu.pe  udKb5ykrC1
2501835         omar.lermab@utec.edu.pe  wbsUCiVrGd

[2501836 rows x 7 columns]

## Agregando profesores, supervisores y administradores al Users.csv

In [ ]:
import pandas as pd
import random
from faker import Faker

fake = Faker('es_ES')

correos_existentes = set(df_users['correo'])

# Contadores de IDs por rol
rol_config = {
    "profesor": {"cantidad": 40, "prefijo": "P"},
    "supervisor": {"cantidad": 4, "prefijo": "S"},
    "admin": {"cantidad": 4, "prefijo": "A"}
}

# Función para generar contraseña
def generar_contraseña():
    return ''.join(random.choices("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890", k=10))

# Función para generar correo con control de duplicados
def generar_correo_unico(nombre, apellido1, apellido2):
    base = f"{nombre[0].lower()}{apellido1.lower()}"
    dominio = "@utec.edu.pe"
    correo = base + dominio

    sufijo = ""
    for letra in apellido2.lower():
        if correo not in correos_existentes:
            break
        sufijo += letra
        correo = base + sufijo + dominio

    contador = 1
    while correo in correos_existentes:
        correo = base + sufijo + str(contador) + dominio
        contador += 1

    correos_existentes.add(correo)
    return correo

nuevos_usuarios = []
for rol, info in rol_config.items():
    for i in range(1, info["cantidad"] + 1):
        nombre_completo = fake.name().split()
        
        if len(nombre_completo) >= 4:
            nombre1, nombre2, apellido1, apellido2 = nombre_completo[:4]
        elif len(nombre_completo) == 3:
            nombre1, nombre2, apellido1 = nombre_completo
            apellido2 = fake.last_name()
        else:
            nombre1 = nombre_completo[0]
            nombre2 = fake.first_name()
            apellido1 = fake.last_name()
            apellido2 = fake.last_name()

        correo = generar_correo_unico(nombre1, apellido1, apellido2)
        contraseña = generar_contraseña()
        registro_id = f"{info['prefijo']}{str(i).zfill(8)}"

        nuevos_usuarios.append({
            "registro_id": registro_id,
            "nombre1": nombre1,
            "nombre2": nombre2,
            "apellido1": apellido1,
            "apellido2": apellido2,
            "correo": correo,
            "contraseña": contraseña
        })

df_nuevos = pd.DataFrame(nuevos_usuarios)

## Limpiado datos

In [ ]:
import unicodedata

def quitar_tildes(texto):
    if isinstance(texto, str):
        return ''.join(
            c for c in unicodedata.normalize('NFKD', texto)
            if not unicodedata.combining(c)
        )
    return texto

columnas_a_limpieza = ['nombre1', 'nombre2', 'apellido1', 'apellido2', 'correo']

for col in columnas_a_limpieza:
    df_users[col] = df_users[col].apply(quitar_tildes)
    df_nuevos[col] = df_nuevos[col].apply(quitar_tildes)

In [ ]:
df_final = pd.concat([df_users, df_nuevos], ignore_index=True)
df_final.to_csv("Users.csv", index=False)

✅ Archivo guardado como usuarios_completos.csv sin tildes.

In [26]:
df_final

,registro_id,nombre1,nombre2,apellido1,apellido2,correo,contraseña
0,E00000001,Maxi,Aragones,Codina,Talavera,maxi.codina@utec.edu.pe,FMa9z2vhgY
1,E00000002,Candelario,Prats,Pozuelo,Torrijos,candelario.pozuelo@utec.edu.pe,6VRBDjaqQ1
2,E00000003,Rosenda,Ester,Boada,Salcedo,rosenda.boada@utec.edu.pe,qaWoCEAOK6
3,E00000004,Xavier,Nicodemo,Castillo,Atienza,xavier.castillo@utec.edu.pe,t1n9lvmB9s
4,E00000005,Marisela,Valentin,Contreras,Camps,marisela.contreras@utec.edu.pe,jCzgtVVRl8
...,...,...,...,...,...,...,...
2501879,S00000004,Silvestre,Figueras,Canete,Ojeda,scanete@utec.edu.pe,ySpHBoIQ5d
2501880,A00000001,Miriam,Anguita,Delgado,Bonilla,mdelgado@utec.edu.pe,jP7P5divlX
2501881,A00000002,Amado,Cesar,Gimeno,Flor,agimeno@utec.edu.pe,DBnGs2fYXp
2501882,A00000003,Celestino,Patricia,Ferrando,Cabezas,cferrando@utec.edu.pe,PUsrYvnTXx
2501883,A00000004,Felipa,Cabrero,Palmer,Pineiro,fpalmer@utec.edu.pe,pJTSljkBpn

## Agregando rol

In [ ]:
def asignar_rol(registro):
    if registro.startswith('E'):
        return 'Estudiante'
    elif registro.startswith('P'):
        return 'Profesor'
    elif registro.startswith('A'):
        return 'Administrador'
    elif registro.startswith('S'):
        return 'Supervisor'
    else:
        return 'Desconocido'

df['rol'] = df['registro_id'].apply(asignar_rol)

# Hashing de contraseñas

In [ ]:
import duckdb

df = duckdb.sql("""
    SELECT 
        *, 
        sha256(contraseña) AS contraseña_hash
    FROM 'Users.csv'
""").df()

if 'contraseña' in df.columns:
    df.drop(columns=['contraseña'], inplace=True)

if 'contraseña_hash' in df.columns:
    df.rename(columns={'contraseña_hash': 'contraseña'}, inplace=True)

df.to_csv('Users.csv', index=False)

print("Archivo 'Users.csv' generado con éxito.")

# Prueba hashing (login)

In [ ]:
import hashlib

def hashear_sha256(contraseña):
    return hashlib.sha256(contraseña.encode('utf-8')).hexdigest()

registro_id_ingresado = input("Registro ID: ")
contraseña_ingresada = input("Contraseña: ")

usuario = df[df['registro_id'] == registro_id_ingresado]

if usuario.empty:
    print("❌ Usuario no encontrado.")
else:
    hash_ingresado = hashear_sha256(contraseña_ingresada)
    hash_guardado = usuario.iloc[0]['contraseña']

    if hash_ingresado == hash_guardado:
        print(f"✅ Bienvenido, {usuario.iloc[0]['nombre1']} ({usuario.iloc[0]['rol']})")
    else:
        print("❌ Contraseña incorrecta.")